name: CI

on:
  push:
    branches: [ main, release/** ]
  pull_request:
    branches: [ main, release/** ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -covermode=count -coverpkg=$(go list ./...) -coverprofile=cover.out
          ./...

      - name: Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: cover.out
